backend:
  name: git-gateway
  branch: main   # of master, afhankelijk van je repo
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "boats"
    label: "Boten"
    folder: "content/boats"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naam", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "string" }
      - { label: "Locatie", name: "locatie", widget: "string" }
      - { label: "Prijs", name: "prijs", widget: "number" }
      - { label: "Afbeelding", name: "image", widget: "image" }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
